#!/usr/bin/env python3
"""
Generate Helm and metrics reference documentation for the agentgateway website.

Reads LINK_VERSION from the environment (values: "latest" or "main") and generates
agentgateway-relevant artifacts from a checked-out agentgateway repo:
- Helm: agentgateway, agentgateway-crds, and agentgateway-standalone charts
  -> assets/agw-docs/pages/reference/helm/{link_version}/
- Metrics: control plane metrics -> assets/agw-docs/snippets/metrics-control-plane-{link_version}.md

API reference docs are generated by the workflow (reference-docs.yaml) and are not handled here.

Usage (from workflow):
  LINK_VERSION=latest python3 scripts/generate-ref-docs.py
  (run from website repo root; agentgateway controller dir is passed via KGATEWAY_DIR=agentgateway/controller)
"""

import os
import platform
import subprocess
import sys


# Agentgateway-only Helm charts: directory under install/helm : output filename
# agentgateway and agentgateway-crds back Kubernetes (xds) mode; agentgateway-standalone
# backs standalone mode. All three live under the same install/helm root, so a chart that
# has not been added to a released tag yet is skipped with a warning rather than failing.
HELM_CHARTS = [
    ("agentgateway", "agentgateway"),
    ("agentgateway-crds", "agentgateway-crds"),
    ("agentgateway-standalone", "agentgateway-standalone"),
]

# Earliest doc version whose docs cover a chart, as (major, minor). The chart can ship in an
# older release without the docs documenting it: agentgateway-standalone exists as far back as
# v1.4.1, but standalone Helm docs start at 1.5. Keyed on DOC_VERSION ("1.5.x") rather than
# LINK_VERSION ("main"/"latest") so that the gate keeps working once 1.5 becomes latest.
CHART_MIN_DOC_VERSION = {
    "agentgateway-standalone": (1, 5),
}


def chart_applies(dir_name: str, doc_version: str) -> bool:
    """Whether the chart is documented for this doc version. Unset DOC_VERSION generates everything."""
    minimum = CHART_MIN_DOC_VERSION.get(dir_name)
    if minimum is None or not doc_version:
        return True
    try:
        major, minor = (int(part) for part in doc_version.split(".")[:2])
    except ValueError:
        print(f"    Warning: cannot parse DOC_VERSION {doc_version!r}; generating {dir_name} anyway")
        return True
    return (major, minor) >= minimum



def merge_cells(description: str, default: str) -> str:
    """Fold a Default cell into a Description cell as a trailing sentence.

    helm-docs always emits a default, even for an undocumented value, so the sentence is
    appended whether or not there is a description to append it to.
    """
    description = description.strip()
    default = default.strip()
    if not default:
        return description
    sentence = f"The default value is {default}."
    if not description:
        return sentence
    if description[-1] not in ".!?:":
        description += "."
    # Markdown cells cannot hold a blank line, so the paragraph break is literal HTML.
    # The site renders goldmark with unsafe: true, so this passes through.
    return f"{description}<br/><br/>{sentence}"


def generate_helm_docs(link_version: str, website_dir: str, kgateway_dir: str, doc_version: str = "") -> bool:
    """Generate Helm chart reference docs for each chart in HELM_CHARTS."""
    print(f"  → Generating Helm docs for {link_version}")

    assets_path = os.path.join(website_dir, "assets", "agw-docs", "pages", "reference", "helm", link_version)
    os.makedirs(assets_path, exist_ok=True)
    generated_any = False

    for dir_name, file_name in HELM_CHARTS:
        if not chart_applies(dir_name, doc_version):
            print(f"    Skipping {file_name}: not documented for {doc_version}")
            continue

        helm_path = os.path.join(kgateway_dir, "install", "helm", dir_name)
        if not os.path.exists(helm_path):
            print(f"    Warning: {helm_path} does not exist, skipping {file_name}")
            continue

        result = subprocess.run(
            [
                "go", "run", "github.com/norwoodj/helm-docs/cmd/helm-docs@v1.14.2",
                f"--chart-search-root={helm_path}",
                "--dry-run",
            ],
            capture_output=True,
            text=True,
            check=True,
        )

        helm_file = os.path.join(assets_path, f"{file_name}.md")
        with open(helm_file, "w") as f:
            f.write(result.stdout)

        # Remove version badge and first 3 lines (title, blank, description)
        if platform.system() == "Darwin":
            subprocess.run(["sed", "-i", "", r"/!\[Version:/,/^$/d", helm_file], check=True)
            subprocess.run(["sed", "-i", "", "1,3d", helm_file], check=True)
        else:
            subprocess.run(["sed", "-i", r"/!\[Version:/,/^$/d", helm_file], check=True)
            subprocess.run(["sed", "-i", "1,3d", helm_file], check=True)

        with open(helm_file, "r", encoding="utf-8") as f:
            content = f.read()

        if "## Values" not in content or ("## Values" in content and "|-----|" not in content):
            note = '\n\n> [!NOTE]\n> No configurable values are currently available for this chart.\n'
            if "[!NOTE]" not in content:
                content = content.rstrip() + note

        # helm-docs emits "| Key | Type | Default | Description |". Fold the default into the
        # description as a trailing sentence and drop the column. A standalone Default column
        # holds a code span, which the browser will not wrap, so it claims a disproportionate
        # share of the table width and squeezes Description to a couple of words per line.
        swapped_lines = []
        in_table = False
        for line in content.splitlines():
            stripped = line.strip()
            if stripped.startswith("| Key ") and "Default" in line and "Description" in line:
                in_table = True
                swapped_lines.append("| Key | Type | Description |")
                continue
            if in_table and stripped.startswith("|-----"):
                swapped_lines.append("|-----|------|-------------|")
                continue
            if in_table and stripped.startswith("|"):
                parts = [p.strip() for p in line.split("|")]
                if len(parts) >= 6:
                    key, typ, default, desc = parts[1], parts[2], parts[3], parts[4]
                    swapped_lines.append(f"| {key} | {typ} | {merge_cells(desc, default)} |")
                else:
                    swapped_lines.append(line)
            else:
                if in_table and not stripped.startswith("|"):
                    in_table = False
                swapped_lines.append(line)
        content = "\n".join(swapped_lines)

        with open(helm_file, "w", encoding="utf-8") as f:
            f.write(content)

        print(f"    ✓ Generated {helm_file}")
        generated_any = True

    return generated_any


def generate_metrics_docs(link_version: str, website_dir: str, kgateway_dir: str) -> bool:
    """Generate control plane metrics into a versioned snippet (e.g. metrics-control-plane-latest.md)."""
    print(f"  → Generating metrics docs for {link_version}")

    snippets_dir = os.path.join(website_dir, "assets", "agw-docs", "snippets")
    os.makedirs(snippets_dir, exist_ok=True)
    out_file = os.path.join(snippets_dir, f"metrics-control-plane-{link_version}.md")

    try:
        result = subprocess.run(
            ["go", "run", "./pkg/metrics/cmd/findmetrics", "--markdown", "."],
            capture_output=True,
            text=True,
            check=True,
            cwd=kgateway_dir,
        )
        md_content = result.stdout
    except subprocess.CalledProcessError as e:
        print(f"    Warning: findmetrics failed: {e.stderr or e}")
        return False

    with open(out_file, "w") as f:
        f.write(md_content)
    print(f"    ✓ Generated {out_file}")
    return True


def main() -> None:
    link_version = os.environ.get("LINK_VERSION", "").strip()
    if not link_version:
        print("Error: LINK_VERSION must be set (e.g. latest, main)")
        sys.exit(1)

    doc_version = os.environ.get("DOC_VERSION", "").strip()
    website_dir = os.environ.get("WEBSITE_DIR", ".")
    kgateway_dir = os.environ.get("KGATEWAY_DIR", "agentgateway/controller")

    if not os.path.isdir(kgateway_dir):
        print(f"Error: agentgateway controller directory not found at {kgateway_dir}")
        sys.exit(1)

    print(f"Generating Helm + metrics for {link_version} (agentgateway/controller at {kgateway_dir})")
    success = 0
    if generate_helm_docs(link_version, website_dir, kgateway_dir, doc_version):
        success += 1
    if generate_metrics_docs(link_version, website_dir, kgateway_dir):
        success += 1
    print(f"Done: generated {success}/2 doc types")


if __name__ == "__main__":
    main()
