#!/usr/bin/env python3
"""Write hugo-local-versions.yaml: a local-only Hugo config overlay that skips
version directories that are not in hugo.yaml's version list.

content/docs/<section>/ holds every version tree this repo has ever had
(1.0.x, 1.1.x, ...), not just the ones in `params.versions`. Hugo builds every
directory it finds, so a local build renders the unlisted trees too: about 60%
of the docs pages. They stay in the repo on purpose (they are still published,
and the enterprise docs read some of them as source), so production builds keep
them. This overlay only speeds up `make serve`.

Nothing is maintained by hand. For each section, the kept versions are the
`linkVersion`s in `params.versions` that apply to it (an entry with no
`sections` applies to all), and every other version-shaped directory is added to
`ignoreFiles`. Add a version to the list and it builds locally again.

If PyYAML is missing, the overlay is written empty and everything builds.
"""

import re
import sys
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parent.parent
CONFIG = REPO_ROOT / "hugo.yaml"
DOCS = REPO_ROOT / "content" / "docs"
OUT = REPO_ROOT / "hugo-local-versions.yaml"

# Directory names that are version trees. Anything else under a section (an
# _index.md, a content adapter, a zip) is never skipped.
VERSION_DIR = re.compile(r"^(?:\d+\.\d+\.(?:x|\d+)|latest|main)$")

HEADER = (
    "# GENERATED by scripts/local-version-config.py for `make serve`.\n"
    "# Gitignored; never pass it to a production build.\n"
)


def main() -> int:
    try:
        import yaml
    except ImportError:
        OUT.write_text(HEADER + "# PyYAML not installed: building every version.\n")
        print("PyYAML not installed (run `make deps`); building every version.")
        return 0

    config = yaml.safe_load(CONFIG.read_text(encoding="utf-8")) or {}
    entries = (config.get("params") or {}).get("versions") or []

    patterns, skipped = [], []
    for section_dir in sorted(p for p in DOCS.iterdir() if p.is_dir()):
        section = section_dir.name
        listed = {
            str(e.get("linkVersion") or e.get("version"))
            for e in entries
            if not e.get("sections") or section in e["sections"]
        }
        for version_dir in sorted(p for p in section_dir.iterdir() if p.is_dir()):
            name = version_dir.name
            if VERSION_DIR.match(name) and name not in listed:
                patterns.append(f"(^|/)content/docs/{re.escape(section)}/{re.escape(name)}/")
                skipped.append(f"{section}/{name}")

    body = "".join(f"  - '{p}'\n" for p in patterns)
    OUT.write_text(HEADER + ("ignoreFiles:\n" + body if body else "ignoreFiles: []\n"), encoding="utf-8")

    if skipped:
        print(
            f"Skipping versions not in hugo.yaml: {', '.join(skipped)}. "
            "Run with FULL=1 to build them."
        )
    return 0


if __name__ == "__main__":
    sys.exit(main())
